/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AuditsRequest,
    AuditsRequestFromJSON,
    AuditsRequestToJSON,
    AuditsResponse,
    AuditsResponseFromJSON,
    AuditsResponseToJSON,
} from '../models';

export interface GetAuditsRequest {
    auditsRequest: AuditsRequest;
}

/**
 * AuditApi - interface
 * 
 * @export
 * @interface AuditApiInterface
 */
export interface AuditApiInterface {
    /**
     * 
     * @summary Audit list
     * @param {AuditsRequest} auditsRequest Get audits request parameters
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApiInterface
     */
    getAuditsRaw(requestParameters: GetAuditsRequest): Promise<runtime.ApiResponse<AuditsResponse>>;

    /**
     * Audit list
     */
    getAudits(requestParameters: GetAuditsRequest): Promise<AuditsResponse>;

}

/**
 * 
 */
export class AuditApi extends runtime.BaseAPI implements AuditApiInterface {

    /**
     * Audit list
     */
    async getAuditsRaw(requestParameters: GetAuditsRequest): Promise<runtime.ApiResponse<AuditsResponse>> {
        if (requestParameters.auditsRequest === null || requestParameters.auditsRequest === undefined) {
            throw new runtime.RequiredError('auditsRequest','Required parameter requestParameters.auditsRequest was null or undefined when calling getAudits.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/audits`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuditsRequestToJSON(requestParameters.auditsRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => AuditsResponseFromJSON(jsonValue));
    }

    /**
     * Audit list
     */
    async getAudits(requestParameters: GetAuditsRequest): Promise<AuditsResponse> {
        const response = await this.getAuditsRaw(requestParameters);
        return await response.value();
    }

}
