/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AuditsRequest,
    AuditsRequestFromJSON,
    AuditsRequestToJSON,
    AuditsResponse,
    AuditsResponseFromJSON,
    AuditsResponseToJSON,
} from '../models';

export interface NgetAuditsRequest {
    auditsRequest: AuditsRequest;
}

/**
 * CauditsApi - interface
 * 
 * @export
 * @interface CauditsApiInterface
 */
export interface CauditsApiInterface {
    /**
     * 
     * @summary Audit list
     * @param {AuditsRequest} auditsRequest Get audits request parameters
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CauditsApiInterface
     */
    ngetAuditsRaw(requestParameters: NgetAuditsRequest): Promise<runtime.ApiResponse<AuditsResponse>>;

    /**
     * Audit list
     */
    ngetAudits(requestParameters: NgetAuditsRequest): Promise<AuditsResponse>;

}

/**
 * 
 */
export class CauditsApi extends runtime.BaseAPI implements CauditsApiInterface {

    /**
     * Audit list
     */
    async ngetAuditsRaw(requestParameters: NgetAuditsRequest): Promise<runtime.ApiResponse<AuditsResponse>> {
        if (requestParameters.auditsRequest === null || requestParameters.auditsRequest === undefined) {
            throw new runtime.RequiredError('auditsRequest','Required parameter requestParameters.auditsRequest was null or undefined when calling ngetAudits.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auditsCur`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuditsRequestToJSON(requestParameters.auditsRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => AuditsResponseFromJSON(jsonValue));
    }

    /**
     * Audit list
     */
    async ngetAudits(requestParameters: NgetAuditsRequest): Promise<AuditsResponse> {
        const response = await this.ngetAuditsRaw(requestParameters);
        return await response.value();
    }

}
