/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    SourceSystemsResponse,
    SourceSystemsResponseFromJSON,
    SourceSystemsResponseToJSON,
} from '../models';

/**
 * SourceSystemApi - interface
 * 
 * @export
 * @interface SourceSystemApiInterface
 */
export interface SourceSystemApiInterface {
    /**
     * 
     * @summary Source system list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceSystemApiInterface
     */
    getSourceSystemsRaw(): Promise<runtime.ApiResponse<SourceSystemsResponse>>;

    /**
     * Source system list
     */
    getSourceSystems(): Promise<SourceSystemsResponse>;

}

/**
 * 
 */
export class SourceSystemApi extends runtime.BaseAPI implements SourceSystemApiInterface {

    /**
     * Source system list
     */
    async getSourceSystemsRaw(): Promise<runtime.ApiResponse<SourceSystemsResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/source-systems`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceSystemsResponseFromJSON(jsonValue));
    }

    /**
     * Source system list
     */
    async getSourceSystems(): Promise<SourceSystemsResponse> {
        const response = await this.getSourceSystemsRaw();
        return await response.value();
    }

}
