/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AuthenticatedUserResponse,
    AuthenticatedUserResponseFromJSON,
    AuthenticatedUserResponseToJSON,
} from '../models';

/**
 * UserApi - interface
 * 
 * @export
 * @interface UserApiInterface
 */
export interface UserApiInterface {
    /**
     * 
     * @summary Authenticated user details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    getAuthenticatedUserRaw(): Promise<runtime.ApiResponse<AuthenticatedUserResponse>>;

    /**
     * Authenticated user details
     */
    getAuthenticatedUser(): Promise<AuthenticatedUserResponse>;

}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI implements UserApiInterface {

    /**
     * Authenticated user details
     */
    async getAuthenticatedUserRaw(): Promise<runtime.ApiResponse<AuthenticatedUserResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/users/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticatedUserResponseFromJSON(jsonValue));
    }

    /**
     * Authenticated user details
     */
    async getAuthenticatedUser(): Promise<AuthenticatedUserResponse> {
        const response = await this.getAuthenticatedUserRaw();
        return await response.value();
    }

}
