/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AuditDataSet {
    CUSTOMER = 'CUSTOMER',
    PRODUCT = 'PRODUCT'
}

export function AuditDataSetFromJSON(json: any): AuditDataSet {
    return AuditDataSetFromJSONTyped(json, false);
}

export function AuditDataSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditDataSet {
    return json as AuditDataSet;
}

export function AuditDataSetToJSON(value?: AuditDataSet | null): any {
    return value as any;
}

