/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface AuthenticatedUserResponse
 */
export interface AuthenticatedUserResponse {
    /**
     * 
     * @type {User}
     * @memberof AuthenticatedUserResponse
     */
    user?: User;
}

export function AuthenticatedUserResponseFromJSON(json: any): AuthenticatedUserResponse {
    return AuthenticatedUserResponseFromJSONTyped(json, false);
}

export function AuthenticatedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatedUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function AuthenticatedUserResponseToJSON(value?: AuthenticatedUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
    };
}


