/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BooleanValue {
    TRUE = 'TRUE',
    FALSE = 'FALSE'
}

export function BooleanValueFromJSON(json: any): BooleanValue {
    return BooleanValueFromJSONTyped(json, false);
}

export function BooleanValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooleanValue {
    return json as BooleanValue;
}

export function BooleanValueToJSON(value?: BooleanValue | null): any {
    return value as any;
}

