/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Customer,
    CustomerFromJSON,
    CustomerFromJSONTyped,
    CustomerToJSON,
    LocalizedCustomerNativeStatus,
    LocalizedCustomerNativeStatusFromJSON,
    LocalizedCustomerNativeStatusFromJSONTyped,
    LocalizedCustomerNativeStatusToJSON,
    LocalizedCustomerState,
    LocalizedCustomerStateFromJSON,
    LocalizedCustomerStateFromJSONTyped,
    LocalizedCustomerStateToJSON,
    LocalizedCustomerType,
    LocalizedCustomerTypeFromJSON,
    LocalizedCustomerTypeFromJSONTyped,
    LocalizedCustomerTypeToJSON,
    LocalizedRejectionReason,
    LocalizedRejectionReasonFromJSON,
    LocalizedRejectionReasonFromJSONTyped,
    LocalizedRejectionReasonToJSON,
    PageInfo,
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomersResponse
 */
export interface CustomersResponse {
    /**
     * 
     * @type {PageInfo}
     * @memberof CustomersResponse
     */
    pageInfo?: PageInfo;
    /**
     * 
     * @type {Array<Customer>}
     * @memberof CustomersResponse
     */
    customers?: Array<Customer>;
    /**
     * 
     * @type {Array<LocalizedCustomerState>}
     * @memberof CustomersResponse
     */
    localizedCustomerStates?: Array<LocalizedCustomerState>;
    /**
     * 
     * @type {Array<LocalizedCustomerNativeStatus>}
     * @memberof CustomersResponse
     */
    localizedCustomerNativeStatuses?: Array<LocalizedCustomerNativeStatus>;
    /**
     * 
     * @type {Array<LocalizedCustomerType>}
     * @memberof CustomersResponse
     */
    localizedCustomerTypes?: Array<LocalizedCustomerType>;
    /**
     * 
     * @type {Array<LocalizedRejectionReason>}
     * @memberof CustomersResponse
     */
    localizedRejectionReasons?: Array<LocalizedRejectionReason>;
}

export function CustomersResponseFromJSON(json: any): CustomersResponse {
    return CustomersResponseFromJSONTyped(json, false);
}

export function CustomersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pageInfo': !exists(json, 'pageInfo') ? undefined : PageInfoFromJSON(json['pageInfo']),
        'customers': !exists(json, 'customers') ? undefined : ((json['customers'] as Array<any>).map(CustomerFromJSON)),
        'localizedCustomerStates': !exists(json, 'localizedCustomerStates') ? undefined : ((json['localizedCustomerStates'] as Array<any>).map(LocalizedCustomerStateFromJSON)),
        'localizedCustomerNativeStatuses': !exists(json, 'localizedCustomerNativeStatuses') ? undefined : ((json['localizedCustomerNativeStatuses'] as Array<any>).map(LocalizedCustomerNativeStatusFromJSON)),
        'localizedCustomerTypes': !exists(json, 'localizedCustomerTypes') ? undefined : ((json['localizedCustomerTypes'] as Array<any>).map(LocalizedCustomerTypeFromJSON)),
        'localizedRejectionReasons': !exists(json, 'localizedRejectionReasons') ? undefined : ((json['localizedRejectionReasons'] as Array<any>).map(LocalizedRejectionReasonFromJSON)),
    };
}

export function CustomersResponseToJSON(value?: CustomersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pageInfo': PageInfoToJSON(value.pageInfo),
        'customers': value.customers === undefined ? undefined : ((value.customers as Array<any>).map(CustomerToJSON)),
        'localizedCustomerStates': value.localizedCustomerStates === undefined ? undefined : ((value.localizedCustomerStates as Array<any>).map(LocalizedCustomerStateToJSON)),
        'localizedCustomerNativeStatuses': value.localizedCustomerNativeStatuses === undefined ? undefined : ((value.localizedCustomerNativeStatuses as Array<any>).map(LocalizedCustomerNativeStatusToJSON)),
        'localizedCustomerTypes': value.localizedCustomerTypes === undefined ? undefined : ((value.localizedCustomerTypes as Array<any>).map(LocalizedCustomerTypeToJSON)),
        'localizedRejectionReasons': value.localizedRejectionReasons === undefined ? undefined : ((value.localizedRejectionReasons as Array<any>).map(LocalizedRejectionReasonToJSON)),
    };
}


