/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerLookup,
    CustomerLookupFromJSON,
    CustomerLookupFromJSONTyped,
    CustomerLookupToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomerLookupResponse
 */
export interface CustomerLookupResponse {
    /**
     * 
     * @type {CustomerLookup}
     * @memberof CustomerLookupResponse
     */
    customerLookup?: CustomerLookup;
}

export function CustomerLookupResponseFromJSON(json: any): CustomerLookupResponse {
    return CustomerLookupResponseFromJSONTyped(json, false);
}

export function CustomerLookupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerLookupResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerLookup': !exists(json, 'customerLookup') ? undefined : CustomerLookupFromJSON(json['customerLookup']),
    };
}

export function CustomerLookupResponseToJSON(value?: CustomerLookupResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customerLookup': CustomerLookupToJSON(value.customerLookup),
    };
}


