/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerNativeStatus,
    CustomerNativeStatusFromJSON,
    CustomerNativeStatusFromJSONTyped,
    CustomerNativeStatusToJSON,
    CustomerState,
    CustomerStateFromJSON,
    CustomerStateFromJSONTyped,
    CustomerStateToJSON,
    CustomerType,
    CustomerTypeFromJSON,
    CustomerTypeFromJSONTyped,
    CustomerTypeToJSON,
    RejectionReason,
    RejectionReasonFromJSON,
    RejectionReasonFromJSONTyped,
    RejectionReasonToJSON,
    SourceSystem,
    SourceSystemFromJSON,
    SourceSystemFromJSONTyped,
    SourceSystemToJSON,
} from './';

/**
 * 
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * 
     * @type {string}
     * @memberof Customer
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Customer
     */
    erpId?: string;
    /**
     * 
     * @type {CustomerType}
     * @memberof Customer
     */
    type?: CustomerType;
    /**
     * 
     * @type {CustomerNativeStatus}
     * @memberof Customer
     */
    nativeStatus?: CustomerNativeStatus;
    /**
     * 
     * @type {string}
     * @memberof Customer
     */
    companyName?: string;
    /**
     * 
     * @type {string}
     * @memberof Customer
     */
    address?: string;
    /**
     * 
     * @type {CustomerState}
     * @memberof Customer
     */
    state?: CustomerState;
    /**
     * 
     * @type {Date}
     * @memberof Customer
     */
    nativeCreatedDate?: Date;
    /**
     * 
     * @type {SourceSystem}
     * @memberof Customer
     */
    sourceSystem?: SourceSystem;
    /**
     * 
     * @type {RejectionReason}
     * @memberof Customer
     */
    rejectionReason?: RejectionReason;
}

export function CustomerFromJSON(json: any): Customer {
    return CustomerFromJSONTyped(json, false);
}

export function CustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Customer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'erpId': !exists(json, 'erpId') ? undefined : json['erpId'],
        'type': !exists(json, 'type') ? undefined : CustomerTypeFromJSON(json['type']),
        'nativeStatus': !exists(json, 'nativeStatus') ? undefined : CustomerNativeStatusFromJSON(json['nativeStatus']),
        'companyName': !exists(json, 'companyName') ? undefined : json['companyName'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'state': !exists(json, 'state') ? undefined : CustomerStateFromJSON(json['state']),
        'nativeCreatedDate': !exists(json, 'nativeCreatedDate') ? undefined : (new Date(json['nativeCreatedDate'])),
        'sourceSystem': !exists(json, 'sourceSystem') ? undefined : SourceSystemFromJSON(json['sourceSystem']),
        'rejectionReason': !exists(json, 'rejectionReason') ? undefined : RejectionReasonFromJSON(json['rejectionReason']),
    };
}

export function CustomerToJSON(value?: Customer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'erpId': value.erpId,
        'type': CustomerTypeToJSON(value.type),
        'nativeStatus': CustomerNativeStatusToJSON(value.nativeStatus),
        'companyName': value.companyName,
        'address': value.address,
        'state': CustomerStateToJSON(value.state),
        'nativeCreatedDate': value.nativeCreatedDate === undefined ? undefined : (value.nativeCreatedDate.toISOString()),
        'sourceSystem': SourceSystemToJSON(value.sourceSystem),
        'rejectionReason': RejectionReasonToJSON(value.rejectionReason),
    };
}


