/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerPartial,
    CustomerPartialFromJSON,
    CustomerPartialFromJSONTyped,
    CustomerPartialToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomerPartialRequest
 */
export interface CustomerPartialRequest {
    /**
     * 
     * @type {CustomerPartial}
     * @memberof CustomerPartialRequest
     */
    customerPartial: CustomerPartial;
}

export function CustomerPartialRequestFromJSON(json: any): CustomerPartialRequest {
    return CustomerPartialRequestFromJSONTyped(json, false);
}

export function CustomerPartialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPartialRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerPartial': CustomerPartialFromJSON(json['customerPartial']),
    };
}

export function CustomerPartialRequestToJSON(value?: CustomerPartialRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customerPartial': CustomerPartialToJSON(value.customerPartial),
    };
}


