/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerDetails,
    CustomerDetailsFromJSON,
    CustomerDetailsFromJSONTyped,
    CustomerDetailsToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomerDetailsResponse
 */
export interface CustomerDetailsResponse {
    /**
     * 
     * @type {CustomerDetails}
     * @memberof CustomerDetailsResponse
     */
    customer?: CustomerDetails;
}

export function CustomerDetailsResponseFromJSON(json: any): CustomerDetailsResponse {
    return CustomerDetailsResponseFromJSONTyped(json, false);
}

export function CustomerDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDetailsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer': !exists(json, 'customer') ? undefined : CustomerDetailsFromJSON(json['customer']),
    };
}

export function CustomerDetailsResponseToJSON(value?: CustomerDetailsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer': CustomerDetailsToJSON(value.customer),
    };
}


