/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CustomerState {
    ACTIVE = 'ACTIVE',
    DELETED = 'DELETED'
}

export function CustomerStateFromJSON(json: any): CustomerState {
    return CustomerStateFromJSONTyped(json, false);
}

export function CustomerStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerState {
    return json as CustomerState;
}

export function CustomerStateToJSON(value?: CustomerState | null): any {
    return value as any;
}

