/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerNativeStatus,
    CustomerNativeStatusFromJSON,
    CustomerNativeStatusFromJSONTyped,
    CustomerNativeStatusToJSON,
    RejectionReason,
    RejectionReasonFromJSON,
    RejectionReasonFromJSONTyped,
    RejectionReasonToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomerPartial
 */
export interface CustomerPartial {
    /**
     * 
     * @type {CustomerNativeStatus}
     * @memberof CustomerPartial
     */
    nativeStatus?: CustomerNativeStatus;
    /**
     * 
     * @type {RejectionReason}
     * @memberof CustomerPartial
     */
    rejectionReason?: RejectionReason;
    /**
     * 
     * @type {string}
     * @memberof CustomerPartial
     */
    freeText?: string;
}

export function CustomerPartialFromJSON(json: any): CustomerPartial {
    return CustomerPartialFromJSONTyped(json, false);
}

export function CustomerPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nativeStatus': !exists(json, 'nativeStatus') ? undefined : CustomerNativeStatusFromJSON(json['nativeStatus']),
        'rejectionReason': !exists(json, 'rejectionReason') ? undefined : RejectionReasonFromJSON(json['rejectionReason']),
        'freeText': !exists(json, 'freeText') ? undefined : json['freeText'],
    };
}

export function CustomerPartialToJSON(value?: CustomerPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nativeStatus': CustomerNativeStatusToJSON(value.nativeStatus),
        'rejectionReason': RejectionReasonToJSON(value.rejectionReason),
        'freeText': value.freeText,
    };
}


