/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CustomerNativeStatus {
    INREVIEW = 'IN_REVIEW',
    VALIDATED = 'VALIDATED',
    BLOCKED = 'BLOCKED'
}

export function CustomerNativeStatusFromJSON(json: any): CustomerNativeStatus {
    return CustomerNativeStatusFromJSONTyped(json, false);
}

export function CustomerNativeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerNativeStatus {
    return json as CustomerNativeStatus;
}

export function CustomerNativeStatusToJSON(value?: CustomerNativeStatus | null): any {
    return value as any;
}

