/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerContactDetails
 */
export interface CustomerContactDetails {
    /**
     * 
     * @type {string}
     * @memberof CustomerContactDetails
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerContactDetails
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerContactDetails
     */
    searchTerms?: string;
}

export function CustomerContactDetailsFromJSON(json: any): CustomerContactDetails {
    return CustomerContactDetailsFromJSONTyped(json, false);
}

export function CustomerContactDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerContactDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'searchTerms': !exists(json, 'searchTerms') ? undefined : json['searchTerms'],
    };
}

export function CustomerContactDetailsToJSON(value?: CustomerContactDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'phoneNumber': value.phoneNumber,
        'searchTerms': value.searchTerms,
    };
}


