/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ErrorCode {
    INTERNALSERVERERROR = 'INTERNAL_SERVER_ERROR',
    BADREQUEST = 'BAD_REQUEST',
    FORBIDDEN = 'FORBIDDEN',
    NOTFOUND = 'NOT_FOUND',
    CONFLICT = 'CONFLICT',
    INCORRECTFREETEXTVALUE = 'INCORRECT_FREE_TEXT_VALUE'
}

export function ErrorCodeFromJSON(json: any): ErrorCode {
    return ErrorCodeFromJSONTyped(json, false);
}

export function ErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCode {
    return json as ErrorCode;
}

export function ErrorCodeToJSON(value?: ErrorCode | null): any {
    return value as any;
}

