/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductAvailability,
    ProductAvailabilityFromJSON,
    ProductAvailabilityFromJSONTyped,
    ProductAvailabilityToJSON,
} from './';

/**
 * 
 * @export
 * @interface LocalizedProductAvailability
 */
export interface LocalizedProductAvailability {
    /**
     * 
     * @type {ProductAvailability}
     * @memberof LocalizedProductAvailability
     */
    availability?: ProductAvailability;
    /**
     * 
     * @type {string}
     * @memberof LocalizedProductAvailability
     */
    localizedAvailability?: string;
}

export function LocalizedProductAvailabilityFromJSON(json: any): LocalizedProductAvailability {
    return LocalizedProductAvailabilityFromJSONTyped(json, false);
}

export function LocalizedProductAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedProductAvailability {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availability': !exists(json, 'availability') ? undefined : ProductAvailabilityFromJSON(json['availability']),
        'localizedAvailability': !exists(json, 'localizedAvailability') ? undefined : json['localizedAvailability'],
    };
}

export function LocalizedProductAvailabilityToJSON(value?: LocalizedProductAvailability | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availability': ProductAvailabilityToJSON(value.availability),
        'localizedAvailability': value.localizedAvailability,
    };
}


