/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ErrorCode,
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './';

/**
 * 
 * @export
 * @interface LocalizedErrorCode
 */
export interface LocalizedErrorCode {
    /**
     * 
     * @type {ErrorCode}
     * @memberof LocalizedErrorCode
     */
    errorCode?: ErrorCode;
    /**
     * 
     * @type {string}
     * @memberof LocalizedErrorCode
     */
    localizedErrorCode?: string;
}

export function LocalizedErrorCodeFromJSON(json: any): LocalizedErrorCode {
    return LocalizedErrorCodeFromJSONTyped(json, false);
}

export function LocalizedErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedErrorCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'errorCode') ? undefined : ErrorCodeFromJSON(json['errorCode']),
        'localizedErrorCode': !exists(json, 'localizedErrorCode') ? undefined : json['localizedErrorCode'],
    };
}

export function LocalizedErrorCodeToJSON(value?: LocalizedErrorCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorCode': ErrorCodeToJSON(value.errorCode),
        'localizedErrorCode': value.localizedErrorCode,
    };
}


