/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BooleanValue,
    BooleanValueFromJSON,
    BooleanValueFromJSONTyped,
    BooleanValueToJSON,
} from './';

/**
 * 
 * @export
 * @interface LocalizedBooleanValue
 */
export interface LocalizedBooleanValue {
    /**
     * 
     * @type {BooleanValue}
     * @memberof LocalizedBooleanValue
     */
    value?: BooleanValue;
    /**
     * 
     * @type {string}
     * @memberof LocalizedBooleanValue
     */
    localizedValue?: string;
}

export function LocalizedBooleanValueFromJSON(json: any): LocalizedBooleanValue {
    return LocalizedBooleanValueFromJSONTyped(json, false);
}

export function LocalizedBooleanValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedBooleanValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : BooleanValueFromJSON(json['value']),
        'localizedValue': !exists(json, 'localizedValue') ? undefined : json['localizedValue'],
    };
}

export function LocalizedBooleanValueToJSON(value?: LocalizedBooleanValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': BooleanValueToJSON(value.value),
        'localizedValue': value.localizedValue,
    };
}


