/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerNativeStatus,
    CustomerNativeStatusFromJSON,
    CustomerNativeStatusFromJSONTyped,
    CustomerNativeStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface LocalizedCustomerNativeStatus
 */
export interface LocalizedCustomerNativeStatus {
    /**
     * 
     * @type {CustomerNativeStatus}
     * @memberof LocalizedCustomerNativeStatus
     */
    nativeStatus?: CustomerNativeStatus;
    /**
     * 
     * @type {string}
     * @memberof LocalizedCustomerNativeStatus
     */
    localizedNativeStatus?: string;
}

export function LocalizedCustomerNativeStatusFromJSON(json: any): LocalizedCustomerNativeStatus {
    return LocalizedCustomerNativeStatusFromJSONTyped(json, false);
}

export function LocalizedCustomerNativeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedCustomerNativeStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nativeStatus': !exists(json, 'nativeStatus') ? undefined : CustomerNativeStatusFromJSON(json['nativeStatus']),
        'localizedNativeStatus': !exists(json, 'localizedNativeStatus') ? undefined : json['localizedNativeStatus'],
    };
}

export function LocalizedCustomerNativeStatusToJSON(value?: LocalizedCustomerNativeStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nativeStatus': CustomerNativeStatusToJSON(value.nativeStatus),
        'localizedNativeStatus': value.localizedNativeStatus,
    };
}


