/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerState,
    CustomerStateFromJSON,
    CustomerStateFromJSONTyped,
    CustomerStateToJSON,
} from './';

/**
 * 
 * @export
 * @interface LocalizedCustomerState
 */
export interface LocalizedCustomerState {
    /**
     * 
     * @type {CustomerState}
     * @memberof LocalizedCustomerState
     */
    state?: CustomerState;
    /**
     * 
     * @type {string}
     * @memberof LocalizedCustomerState
     */
    localizedState?: string;
}

export function LocalizedCustomerStateFromJSON(json: any): LocalizedCustomerState {
    return LocalizedCustomerStateFromJSONTyped(json, false);
}

export function LocalizedCustomerStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedCustomerState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': !exists(json, 'state') ? undefined : CustomerStateFromJSON(json['state']),
        'localizedState': !exists(json, 'localizedState') ? undefined : json['localizedState'],
    };
}

export function LocalizedCustomerStateToJSON(value?: LocalizedCustomerState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': CustomerStateToJSON(value.state),
        'localizedState': value.localizedState,
    };
}


