/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RejectionReason,
    RejectionReasonFromJSON,
    RejectionReasonFromJSONTyped,
    RejectionReasonToJSON,
} from './';

/**
 * 
 * @export
 * @interface LocalizedRejectionReason
 */
export interface LocalizedRejectionReason {
    /**
     * 
     * @type {RejectionReason}
     * @memberof LocalizedRejectionReason
     */
    rejectionReason?: RejectionReason;
    /**
     * 
     * @type {string}
     * @memberof LocalizedRejectionReason
     */
    localizedRejectionReason?: string;
}

export function LocalizedRejectionReasonFromJSON(json: any): LocalizedRejectionReason {
    return LocalizedRejectionReasonFromJSONTyped(json, false);
}

export function LocalizedRejectionReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedRejectionReason {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rejectionReason': !exists(json, 'rejectionReason') ? undefined : RejectionReasonFromJSON(json['rejectionReason']),
        'localizedRejectionReason': !exists(json, 'localizedRejectionReason') ? undefined : json['localizedRejectionReason'],
    };
}

export function LocalizedRejectionReasonToJSON(value?: LocalizedRejectionReason | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rejectionReason': RejectionReasonToJSON(value.rejectionReason),
        'localizedRejectionReason': value.localizedRejectionReason,
    };
}


