/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerType,
    CustomerTypeFromJSON,
    CustomerTypeFromJSONTyped,
    CustomerTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface LocalizedCustomerType
 */
export interface LocalizedCustomerType {
    /**
     * 
     * @type {CustomerType}
     * @memberof LocalizedCustomerType
     */
    type?: CustomerType;
    /**
     * 
     * @type {string}
     * @memberof LocalizedCustomerType
     */
    localizedType?: string;
}

export function LocalizedCustomerTypeFromJSON(json: any): LocalizedCustomerType {
    return LocalizedCustomerTypeFromJSONTyped(json, false);
}

export function LocalizedCustomerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedCustomerType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : CustomerTypeFromJSON(json['type']),
        'localizedType': !exists(json, 'localizedType') ? undefined : json['localizedType'],
    };
}

export function LocalizedCustomerTypeToJSON(value?: LocalizedCustomerType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': CustomerTypeToJSON(value.type),
        'localizedType': value.localizedType,
    };
}


