/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum NullableBooleanValue {
    TRUE = 'TRUE',
    FALSE = 'FALSE'
}

export function NullableBooleanValueFromJSON(json: any): NullableBooleanValue {
    return NullableBooleanValueFromJSONTyped(json, false);
}

export function NullableBooleanValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableBooleanValue {
    return json as NullableBooleanValue;
}

export function NullableBooleanValueToJSON(value?: NullableBooleanValue | null): any {
    return value as any;
}

