/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum NullableProductAvailability {
    AVAILABLE = 'AVAILABLE',
    NOTAVAILABLE = 'NOT_AVAILABLE',
    SHORTTERMNOTAVAILABLE = 'SHORT_TERM_NOT_AVAILABLE',
    MEDIUMTERMNOTAVAILABLE = 'MEDIUM_TERM_NOT_AVAILABLE',
    LONGTERMNOTAVAILABLE = 'LONG_TERM_NOT_AVAILABLE'
}

export function NullableProductAvailabilityFromJSON(json: any): NullableProductAvailability {
    return NullableProductAvailabilityFromJSONTyped(json, false);
}

export function NullableProductAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableProductAvailability {
    return json as NullableProductAvailability;
}

export function NullableProductAvailabilityToJSON(value?: NullableProductAvailability | null): any {
    return value as any;
}

