/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NullableBooleanValue,
    NullableBooleanValueFromJSON,
    NullableBooleanValueFromJSONTyped,
    NullableBooleanValueToJSON,
    NullableProductAvailability,
    NullableProductAvailabilityFromJSON,
    NullableProductAvailabilityFromJSONTyped,
    NullableProductAvailabilityToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductPartial
 */
export interface ProductPartial {
    /**
     * 
     * @type {NullableBooleanValue}
     * @memberof ProductPartial
     */
    isVisible?: NullableBooleanValue | null;
    /**
     * 
     * @type {NullableProductAvailability}
     * @memberof ProductPartial
     */
    availability?: NullableProductAvailability | null;
    /**
     * 
     * @type {number}
     * @memberof ProductPartial
     */
    minimumOrderQuantity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductPartial
     */
    maximumOrderQuantity?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProductPartial
     */
    associatedProducts?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductPartial
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductPartial
     */
    imageFilename?: string | null;
}

export function ProductPartialFromJSON(json: any): ProductPartial {
    return ProductPartialFromJSONTyped(json, false);
}

export function ProductPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isVisible': !exists(json, 'isVisible') ? undefined : NullableBooleanValueFromJSON(json['isVisible']),
        'availability': !exists(json, 'availability') ? undefined : NullableProductAvailabilityFromJSON(json['availability']),
        'minimumOrderQuantity': !exists(json, 'minimumOrderQuantity') ? undefined : json['minimumOrderQuantity'],
        'maximumOrderQuantity': !exists(json, 'maximumOrderQuantity') ? undefined : json['maximumOrderQuantity'],
        'associatedProducts': !exists(json, 'associatedProducts') ? undefined : json['associatedProducts'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'imageFilename': !exists(json, 'imageFilename') ? undefined : json['imageFilename'],
    };
}

export function ProductPartialToJSON(value?: ProductPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isVisible': NullableBooleanValueToJSON(value.isVisible),
        'availability': NullableProductAvailabilityToJSON(value.availability),
        'minimumOrderQuantity': value.minimumOrderQuantity,
        'maximumOrderQuantity': value.maximumOrderQuantity,
        'associatedProducts': value.associatedProducts,
        'image': value.image,
        'imageFilename': value.imageFilename,
    };
}


