/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PageInfo,
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
    Product,
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductsResponse
 */
export interface ProductsResponse {
    /**
     * 
     * @type {PageInfo}
     * @memberof ProductsResponse
     */
    pageInfo?: PageInfo;
    /**
     * 
     * @type {Array<Product>}
     * @memberof ProductsResponse
     */
    products?: Array<Product>;
}

export function ProductsResponseFromJSON(json: any): ProductsResponse {
    return ProductsResponseFromJSONTyped(json, false);
}

export function ProductsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pageInfo': !exists(json, 'pageInfo') ? undefined : PageInfoFromJSON(json['pageInfo']),
        'products': !exists(json, 'products') ? undefined : ((json['products'] as Array<any>).map(ProductFromJSON)),
    };
}

export function ProductsResponseToJSON(value?: ProductsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pageInfo': PageInfoToJSON(value.pageInfo),
        'products': value.products === undefined ? undefined : ((value.products as Array<any>).map(ProductToJSON)),
    };
}


