/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BooleanValue,
    BooleanValueFromJSON,
    BooleanValueFromJSONTyped,
    BooleanValueToJSON,
    ProductAvailability,
    ProductAvailabilityFromJSON,
    ProductAvailabilityFromJSONTyped,
    ProductAvailabilityToJSON,
    SourceSystem,
    SourceSystemFromJSON,
    SourceSystemFromJSONTyped,
    SourceSystemToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductDetails
 */
export interface ProductDetails {
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    id?: string;
    /**
     * 
     * @type {BooleanValue}
     * @memberof ProductDetails
     */
    isVisible?: BooleanValue;
    /**
     * 
     * @type {ProductAvailability}
     * @memberof ProductDetails
     */
    availability?: ProductAvailability;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    statusId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductDetails
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDetails
     */
    minimumOrderQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDetails
     */
    maximumOrderQuantity?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    associatedProducts?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    imageFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetails
     */
    imageFilepath?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductDetails
     */
    imageUploadDate?: Date;
    /**
     * 
     * @type {SourceSystem}
     * @memberof ProductDetails
     */
    sourceSystem?: SourceSystem;
}

export function ProductDetailsFromJSON(json: any): ProductDetails {
    return ProductDetailsFromJSONTyped(json, false);
}

export function ProductDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'isVisible': !exists(json, 'isVisible') ? undefined : BooleanValueFromJSON(json['isVisible']),
        'availability': !exists(json, 'availability') ? undefined : ProductAvailabilityFromJSON(json['availability']),
        'statusId': !exists(json, 'statusId') ? undefined : json['statusId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'minimumOrderQuantity': !exists(json, 'minimumOrderQuantity') ? undefined : json['minimumOrderQuantity'],
        'maximumOrderQuantity': !exists(json, 'maximumOrderQuantity') ? undefined : json['maximumOrderQuantity'],
        'associatedProducts': !exists(json, 'associatedProducts') ? undefined : json['associatedProducts'],
        'imageFilename': !exists(json, 'imageFilename') ? undefined : json['imageFilename'],
        'imageFilepath': !exists(json, 'imageFilepath') ? undefined : json['imageFilepath'],
        'imageUploadDate': !exists(json, 'imageUploadDate') ? undefined : (new Date(json['imageUploadDate'])),
        'sourceSystem': !exists(json, 'sourceSystem') ? undefined : SourceSystemFromJSON(json['sourceSystem']),
    };
}

export function ProductDetailsToJSON(value?: ProductDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'isVisible': BooleanValueToJSON(value.isVisible),
        'availability': ProductAvailabilityToJSON(value.availability),
        'statusId': value.statusId,
        'name': value.name,
        'description': value.description,
        'price': value.price,
        'minimumOrderQuantity': value.minimumOrderQuantity,
        'maximumOrderQuantity': value.maximumOrderQuantity,
        'associatedProducts': value.associatedProducts,
        'imageFilename': value.imageFilename,
        'imageFilepath': value.imageFilepath,
        'imageUploadDate': value.imageUploadDate === undefined ? undefined : (value.imageUploadDate.toISOString()),
        'sourceSystem': SourceSystemToJSON(value.sourceSystem),
    };
}


