/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BooleanValue,
    BooleanValueFromJSON,
    BooleanValueFromJSONTyped,
    BooleanValueToJSON,
    ProductAvailability,
    ProductAvailabilityFromJSON,
    ProductAvailabilityFromJSONTyped,
    ProductAvailabilityToJSON,
    SourceSystem,
    SourceSystemFromJSON,
    SourceSystemFromJSONTyped,
    SourceSystemToJSON,
} from './';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    statusId?: string;
    /**
     * 
     * @type {BooleanValue}
     * @memberof Product
     */
    isVisible?: BooleanValue;
    /**
     * 
     * @type {ProductAvailability}
     * @memberof Product
     */
    availability?: ProductAvailability;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    minimumOrderQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    maximumOrderQuantity?: number;
    /**
     * 
     * @type {BooleanValue}
     * @memberof Product
     */
    hasMedia?: BooleanValue;
    /**
     * 
     * @type {SourceSystem}
     * @memberof Product
     */
    sourceSystem?: SourceSystem;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'statusId': !exists(json, 'statusId') ? undefined : json['statusId'],
        'isVisible': !exists(json, 'isVisible') ? undefined : BooleanValueFromJSON(json['isVisible']),
        'availability': !exists(json, 'availability') ? undefined : ProductAvailabilityFromJSON(json['availability']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'minimumOrderQuantity': !exists(json, 'minimumOrderQuantity') ? undefined : json['minimumOrderQuantity'],
        'maximumOrderQuantity': !exists(json, 'maximumOrderQuantity') ? undefined : json['maximumOrderQuantity'],
        'hasMedia': !exists(json, 'hasMedia') ? undefined : BooleanValueFromJSON(json['hasMedia']),
        'sourceSystem': !exists(json, 'sourceSystem') ? undefined : SourceSystemFromJSON(json['sourceSystem']),
    };
}

export function ProductToJSON(value?: Product | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'statusId': value.statusId,
        'isVisible': BooleanValueToJSON(value.isVisible),
        'availability': ProductAvailabilityToJSON(value.availability),
        'description': value.description,
        'minimumOrderQuantity': value.minimumOrderQuantity,
        'maximumOrderQuantity': value.maximumOrderQuantity,
        'hasMedia': BooleanValueToJSON(value.hasMedia),
        'sourceSystem': SourceSystemToJSON(value.sourceSystem),
    };
}


