/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Language,
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    SearchProductsBy,
    SearchProductsByFromJSON,
    SearchProductsByFromJSONTyped,
    SearchProductsByToJSON,
    SortDirection,
    SortDirectionFromJSON,
    SortDirectionFromJSONTyped,
    SortDirectionToJSON,
    SortProductsBy,
    SortProductsByFromJSON,
    SortProductsByFromJSONTyped,
    SortProductsByToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductsRequest
 */
export interface ProductsRequest {
    /**
     * 
     * @type {number}
     * @memberof ProductsRequest
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsRequest
     */
    pageNumber?: number;
    /**
     * 
     * @type {SortProductsBy}
     * @memberof ProductsRequest
     */
    sortBy: SortProductsBy;
    /**
     * 
     * @type {SortDirection}
     * @memberof ProductsRequest
     */
    sortDirection: SortDirection;
    /**
     * 
     * @type {Array<SearchProductsBy>}
     * @memberof ProductsRequest
     */
    filters?: Array<SearchProductsBy>;
    /**
     * 
     * @type {Language}
     * @memberof ProductsRequest
     */
    language: Language;
}

export function ProductsRequestFromJSON(json: any): ProductsRequest {
    return ProductsRequestFromJSONTyped(json, false);
}

export function ProductsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'sortBy': SortProductsByFromJSON(json['sortBy']),
        'sortDirection': SortDirectionFromJSON(json['sortDirection']),
        'filters': !exists(json, 'filters') ? undefined : ((json['filters'] as Array<any>).map(SearchProductsByFromJSON)),
        'language': LanguageFromJSON(json['language']),
    };
}

export function ProductsRequestToJSON(value?: ProductsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pageSize': value.pageSize,
        'pageNumber': value.pageNumber,
        'sortBy': SortProductsByToJSON(value.sortBy),
        'sortDirection': SortDirectionToJSON(value.sortDirection),
        'filters': value.filters === undefined ? undefined : ((value.filters as Array<any>).map(SearchProductsByToJSON)),
        'language': LanguageToJSON(value.language),
    };
}


