/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductPartial,
    ProductPartialFromJSON,
    ProductPartialFromJSONTyped,
    ProductPartialToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductPartialRequest
 */
export interface ProductPartialRequest {
    /**
     * 
     * @type {ProductPartial}
     * @memberof ProductPartialRequest
     */
    productPartial: ProductPartial;
}

export function ProductPartialRequestFromJSON(json: any): ProductPartialRequest {
    return ProductPartialRequestFromJSONTyped(json, false);
}

export function ProductPartialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPartialRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productPartial': ProductPartialFromJSON(json['productPartial']),
    };
}

export function ProductPartialRequestToJSON(value?: ProductPartialRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productPartial': ProductPartialToJSON(value.productPartial),
    };
}


