/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductDetails,
    ProductDetailsFromJSON,
    ProductDetailsFromJSONTyped,
    ProductDetailsToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductDetailsResponse
 */
export interface ProductDetailsResponse {
    /**
     * 
     * @type {ProductDetails}
     * @memberof ProductDetailsResponse
     */
    product?: ProductDetails;
}

export function ProductDetailsResponseFromJSON(json: any): ProductDetailsResponse {
    return ProductDetailsResponseFromJSONTyped(json, false);
}

export function ProductDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDetailsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'product': !exists(json, 'product') ? undefined : ProductDetailsFromJSON(json['product']),
    };
}

export function ProductDetailsResponseToJSON(value?: ProductDetailsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product': ProductDetailsToJSON(value.product),
    };
}


