/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProductAvailability {
    AVAILABLE = 'AVAILABLE',
    NOTAVAILABLE = 'NOT_AVAILABLE',
    SHORTTERMNOTAVAILABLE = 'SHORT_TERM_NOT_AVAILABLE',
    MEDIUMTERMNOTAVAILABLE = 'MEDIUM_TERM_NOT_AVAILABLE',
    LONGTERMNOTAVAILABLE = 'LONG_TERM_NOT_AVAILABLE'
}

export function ProductAvailabilityFromJSON(json: any): ProductAvailability {
    return ProductAvailabilityFromJSONTyped(json, false);
}

export function ProductAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductAvailability {
    return json as ProductAvailability;
}

export function ProductAvailabilityToJSON(value?: ProductAvailability | null): any {
    return value as any;
}

