/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RejectionReason {
    ADDRESS = 'ADDRESS',
    NAME = 'NAME',
    OTHER = 'OTHER',
    REFERENCE = 'REFERENCE'
}

export function RejectionReasonFromJSON(json: any): RejectionReason {
    return RejectionReasonFromJSONTyped(json, false);
}

export function RejectionReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): RejectionReason {
    return json as RejectionReason;
}

export function RejectionReasonToJSON(value?: RejectionReason | null): any {
    return value as any;
}

