/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SearchByOperation,
    SearchByOperationFromJSON,
    SearchByOperationFromJSONTyped,
    SearchByOperationToJSON,
    SearchProductsByField,
    SearchProductsByFieldFromJSON,
    SearchProductsByFieldFromJSONTyped,
    SearchProductsByFieldToJSON,
} from './';

/**
 * 
 * @export
 * @interface SearchProductsBy
 */
export interface SearchProductsBy {
    /**
     * 
     * @type {SearchProductsByField}
     * @memberof SearchProductsBy
     */
    field?: SearchProductsByField;
    /**
     * 
     * @type {SearchByOperation}
     * @memberof SearchProductsBy
     */
    operation?: SearchByOperation;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchProductsBy
     */
    values?: Array<string>;
}

export function SearchProductsByFromJSON(json: any): SearchProductsBy {
    return SearchProductsByFromJSONTyped(json, false);
}

export function SearchProductsByFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchProductsBy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': !exists(json, 'field') ? undefined : SearchProductsByFieldFromJSON(json['field']),
        'operation': !exists(json, 'operation') ? undefined : SearchByOperationFromJSON(json['operation']),
        'values': !exists(json, 'values') ? undefined : json['values'],
    };
}

export function SearchProductsByToJSON(value?: SearchProductsBy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': SearchProductsByFieldToJSON(value.field),
        'operation': SearchByOperationToJSON(value.operation),
        'values': value.values,
    };
}


