/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SearchProductsByField {
    ISVISIBLE = 'IS_VISIBLE',
    AVAILABILITY = 'AVAILABILITY',
    PRODUCTID = 'PRODUCT_ID',
    DESCRIPTION = 'DESCRIPTION',
    MINIMUMORDERQUANTITY = 'MINIMUM_ORDER_QUANTITY',
    MAXIMUMORDERQUANTITY = 'MAXIMUM_ORDER_QUANTITY',
    HASMEDIA = 'HAS_MEDIA',
    SOURCE = 'SOURCE'
}

export function SearchProductsByFieldFromJSON(json: any): SearchProductsByField {
    return SearchProductsByFieldFromJSONTyped(json, false);
}

export function SearchProductsByFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchProductsByField {
    return json as SearchProductsByField;
}

export function SearchProductsByFieldToJSON(value?: SearchProductsByField | null): any {
    return value as any;
}

