/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SearchAuditsByField,
    SearchAuditsByFieldFromJSON,
    SearchAuditsByFieldFromJSONTyped,
    SearchAuditsByFieldToJSON,
    SearchByOperation,
    SearchByOperationFromJSON,
    SearchByOperationFromJSONTyped,
    SearchByOperationToJSON,
} from './';

/**
 * 
 * @export
 * @interface SearchAuditsBy
 */
export interface SearchAuditsBy {
    /**
     * 
     * @type {SearchAuditsByField}
     * @memberof SearchAuditsBy
     */
    field?: SearchAuditsByField;
    /**
     * 
     * @type {SearchByOperation}
     * @memberof SearchAuditsBy
     */
    operation?: SearchByOperation;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchAuditsBy
     */
    values?: Array<string>;
}

export function SearchAuditsByFromJSON(json: any): SearchAuditsBy {
    return SearchAuditsByFromJSONTyped(json, false);
}

export function SearchAuditsByFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAuditsBy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': !exists(json, 'field') ? undefined : SearchAuditsByFieldFromJSON(json['field']),
        'operation': !exists(json, 'operation') ? undefined : SearchByOperationFromJSON(json['operation']),
        'values': !exists(json, 'values') ? undefined : json['values'],
    };
}

export function SearchAuditsByToJSON(value?: SearchAuditsBy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': SearchAuditsByFieldToJSON(value.field),
        'operation': SearchByOperationToJSON(value.operation),
        'values': value.values,
    };
}


