/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SearchCustomersByField {
    NATIVESTATUS = 'NATIVE_STATUS',
    ERPID = 'ERP_ID',
    COMPANYNAME = 'COMPANY_NAME',
    ADDRESS = 'ADDRESS',
    STATE = 'STATE',
    TYPE = 'TYPE',
    NATIVECREATEDDATE = 'NATIVE_CREATED_DATE',
    SOURCE = 'SOURCE',
    REJECTIONREASON = 'REJECTION_REASON'
}

export function SearchCustomersByFieldFromJSON(json: any): SearchCustomersByField {
    return SearchCustomersByFieldFromJSONTyped(json, false);
}

export function SearchCustomersByFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchCustomersByField {
    return json as SearchCustomersByField;
}

export function SearchCustomersByFieldToJSON(value?: SearchCustomersByField | null): any {
    return value as any;
}

