/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SearchByOperation {
    IN = 'IN',
    LIKE = 'LIKE'
}

export function SearchByOperationFromJSON(json: any): SearchByOperation {
    return SearchByOperationFromJSONTyped(json, false);
}

export function SearchByOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchByOperation {
    return json as SearchByOperation;
}

export function SearchByOperationToJSON(value?: SearchByOperation | null): any {
    return value as any;
}

