/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SearchAuditsByField {
    DATASET = 'DATA_SET',
    HEADER = 'HEADER',
    MESSAGE = 'MESSAGE',
    INITIATOR = 'INITIATOR',
    DATE = 'DATE'
}

export function SearchAuditsByFieldFromJSON(json: any): SearchAuditsByField {
    return SearchAuditsByFieldFromJSONTyped(json, false);
}

export function SearchAuditsByFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAuditsByField {
    return json as SearchAuditsByField;
}

export function SearchAuditsByFieldToJSON(value?: SearchAuditsByField | null): any {
    return value as any;
}

