/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SortAuditsBy {
    DATASET = 'DATA_SET',
    HEADER = 'HEADER',
    MESSAGE = 'MESSAGE',
    INITIATOR = 'INITIATOR',
    DATE = 'DATE'
}

export function SortAuditsByFromJSON(json: any): SortAuditsBy {
    return SortAuditsByFromJSONTyped(json, false);
}

export function SortAuditsByFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortAuditsBy {
    return json as SortAuditsBy;
}

export function SortAuditsByToJSON(value?: SortAuditsBy | null): any {
    return value as any;
}

