/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceSystem
 */
export interface SourceSystem {
    /**
     * 
     * @type {string}
     * @memberof SourceSystem
     */
    name: string;
}

export function SourceSystemFromJSON(json: any): SourceSystem {
    return SourceSystemFromJSONTyped(json, false);
}

export function SourceSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceSystem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function SourceSystemToJSON(value?: SourceSystem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


