/* tslint:disable */
/* eslint-disable */
/**
 * ZMDS API documentation
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SourceSystem,
    SourceSystemFromJSON,
    SourceSystemFromJSONTyped,
    SourceSystemToJSON,
} from './';

/**
 * 
 * @export
 * @interface SourceSystemsResponse
 */
export interface SourceSystemsResponse {
    /**
     * 
     * @type {Array<SourceSystem>}
     * @memberof SourceSystemsResponse
     */
    sourceSystems?: Array<SourceSystem>;
}

export function SourceSystemsResponseFromJSON(json: any): SourceSystemsResponse {
    return SourceSystemsResponseFromJSONTyped(json, false);
}

export function SourceSystemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceSystemsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceSystems': !exists(json, 'sourceSystems') ? undefined : ((json['sourceSystems'] as Array<any>).map(SourceSystemFromJSON)),
    };
}

export function SourceSystemsResponseToJSON(value?: SourceSystemsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sourceSystems': value.sourceSystems === undefined ? undefined : ((value.sourceSystems as Array<any>).map(SourceSystemToJSON)),
    };
}


