# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.9.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        #here the node version which is required

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ./init.sh 
      working-directory: \a\ZMDS_FRONTEND\ZMDS_FRONTEND\tools\api-generator\
    - run: ./gen_sdk.sh
      working-directory: \a\ZMDS_FRONTEND\ZMDS_FRONTEND\tools\api-generator\
    - run: npm install 
      working-directory: clientside
    - run: npm run build 
      working-directory: clientside
      
    - name:  Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
          name: download_Build
          path: \a\ZMDS_FRONTEND\ZMDS_FRONTEND\clientside\build\
